version: "3"

services:
  fakeapserver:
    build:
      context: .
      dockerfile: Dockerfile-fakeapserver
      args:
        - AP_API_KEY
    ports:
      # The admin pane will be exposed on the host machine at
      # http://localhost:8002/elections/2016/ap-deja-vu/
      - "8002:8002"

  database:
    image: "postgres:10"
    environment:
      - POSTGRES_USER=elections18
    ports:
      - "5433:5432"

  bootstrap_db:
    depends_on:
      - database
      - fakeapserver
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "fab --fabfile=/opt/elections18/fabfile data.bootstrap_db"
    volumes:
      - .:/opt/elections18
    environment:
      - elections18_POSTGRES_HOST=database
      - AP_API_BASE_URL=http://fakeapserver:8002/elections/2016/ap-deja-vu
      - AP_API_KEY

  daemon:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "fab --fabfile=/opt/elections18/fabfile daemons.main"
    volumes:
      - .:/opt/elections18
      # This allows rendered data to be shared with the front-end repo
      - ../elections18-graphics:/opt/elections18-graphics
    environment:
      - elections18_POSTGRES_HOST=database
      - AP_API_BASE_URL=http://fakeapserver:8002/elections/2016/ap-deja-vu
      - AP_API_KEY

  app:
    depends_on:
      - database
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: "fab --fabfile=/opt/elections18/fabfile app:8001"
    ports:
      # The admin pane will be exposed on the host machine at
      # http://localhost:8001/elections18/calls/senate/
      # (or altered for other office types)
      - "8001:8001"
    volumes:
      - .:/opt/elections18
    environment:
      - elections18_POSTGRES_HOST=database
